import type { Config } from 'tailwindcss';

const config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  safelist: [{ pattern: /text-tagColor-\d+/ }, { pattern: /bg-tagBgColor-\d+/ }],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        // add color
        black: {
          400: '#2E2E3A',
          500: '#21212A',
          600: '#17171C',
        },
        white: '#F1F1F5',
        gray: {
          500: '#9FA6B2',
          600: '#6E6E82',
        },
        blue: '#5097FA',
        indigo: '#5363FF',
        yellow: '#FFC83C',
        green: '#05D58B',
        pink: '#FF2F9F',
        red: '#FF0000',
        tagColor: {
          '0': '#C5D17C',
          '1': '#F75532',
          '2': '#A952FF',
          '3': '#49AF1A',
          '4': '#D676C1',
          '5': '#FF7E46',
          '6': '#23B581',
          '7': '#FD529A',
          '8': '#747AFF',
          '9': '#3098E3',
          '10': '#FFBB00',
          '11': '#76C7C0',
          '12': '#FF6F61',
          '13': '#5B84B1',
          '14': '#9B2335',
          '15': '#FFA500',
          '16': '#A1C181',
          '17': '#FFD700',
          '18': '#B565A7',
          '19': '#FFB6C1',
          '20': '#8A2BE2',
          '21': '#7FFF00',
          '22': '#DC143C',
          '23': '#00CED1',
          '24': '#9400D3',
          '25': '#FF1493',
          '26': '#00BFFF',
          '27': '#FF69B4',
          '28': '#CD5C5C',
          '29': '#4B0082',
          '30': '#9fa6b2',
        },
        tagBgColor: {
          '0': '#2D2E2B',
          '1': '#322124',
          '2': '#2A2138',
          '3': '#202A22',
          '4': '#2E2532',
          '5': '#322626',
          '6': '#1C2B2C',
          '7': '#32212E',
          '8': '#252538',
          '9': '#1E2836',
          '10': '#33312D',
          '11': '#2A2E2F',
          '12': '#2E2827',
          '13': '#1E2A36',
          '14': '#30272A',
          '15': '#332B1C',
          '16': '#2B322D',
          '17': '#332D1C',
          '18': '#2F2A32',
          '19': '#32242A',
          '20': '#251E2B',
          '21': '#1E2D22',
          '22': '#32202B',
          '23': '#1C2B32',
          '24': '#2A2132',
          '25': '#32202E',
          '26': '#1E2832',
          '27': '#32212A',
          '28': '#2B2527',
          '29': '#2D2732',
          '30': '#292a31',
        },
      },
      gradation: 'linear-gradient(to right, #5097FA, #5363FF)',
      // fill button
      backgroundImage: (theme) => ({
        gradation: 'linear-gradient(to right, #5097FA, #5363FF)',
        'gradation-hover': 'linear-gradient(to right, #353542, #353542)',
      }),
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  variants: {
    extend: {
      backgroundImage: ['hover'], // hover 변형을 추가
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;

export default config;
