import QueryProviderWrapper from '@/components/QueryProviderWrapper';
import { Provider } from '@/components/SessionProvider';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';
import FloatAddButton from './_styled-guide/_components/float-add-button';
import Gnb from './_styled-guide/_components/gnb';
import { authOptions } from './api/auth/[...nextauth]/auth-options';
import './globals.css';
import KakaoScript from './product/[productId]/_components/product-detail/kakao-script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Mogazoa',
  description: 'Generated by create next app',
};

declare global {
  interface Window {
    Kakao: any;
  }
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="ko">
      <body className={(inter.className, 'bg-BgBlack px-5 pt-[70px] md:pt-[80px] lg:pt-[100px]')}>
        <QueryProviderWrapper>
          <Provider>
            <Gnb isLogin={!!session} />
            {children}
            {!!session && <FloatAddButton />}
          </Provider>
        </QueryProviderWrapper>
        <Toaster position="top-center" />
        <KakaoScript />
      </body>
    </html>
  );
}
