import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import QueryProviderWrapper from '@/components/QueryProviderWrapper';
import KakaoScript from './_styled-guide/_components/KaKaoScript';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

declare global {
  interface Window {
    Kakao: any;
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <QueryProviderWrapper>{children}</QueryProviderWrapper>
      </body>
      <KakaoScript />
    </html>
  );
}
