import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import QueryProviderWrapper from '@/components/QueryProviderWrapper';
import { cn } from '@/lib/utils';
import { Provider } from '@/components/SessionProvider';
import type { Session } from 'next-auth';
import { Toaster } from 'sonner';
import KakaoScript from './_styled-guide/_components/KaKaoScript';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

declare global {
  interface Window {
    Kakao: any;
  }
}

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: Session | null;
}>) {
  return (
    <html lang="ko">
      <body className={cn(inter.className, 'bg-BgBlack')}>
        <QueryProviderWrapper>
          <Provider session={session}>{children}</Provider>
        </QueryProviderWrapper>
        <Toaster position="top-center" />
      </body>
      <KakaoScript />
    </html>
  );
}
